### ISSUE TITLE
unlock delayed for 30 seconds when wireless network connection active

### ISSUE THREAD

**Issue by Konfekt** [google/xsecurelock#10]
Lock the screen by `xsecurelock`, type the correct password and hit `enter`.

With an active wireless network connection, it takes 30 to unlock the screen.
With no active wireless network connection, the screen is immediately unlocked (for example after disabling the wireless network service by a hotkey when the screen is locked).

How to make xsecurelock unlock the screen immediately, even with an active wireless network connection?

**Comment by divVerent** [comment]
I don't know how this has anything to do with the wireless connection and cannot reproduce it. I suspect this is a PAM issue on your side, like, PAM somehow/somewhere trying to resolve a name (maybe your host name) which runs into a timeout when connected, and fails immediately when not connected.

Things I'd check first:

- Is your hostname (run: hostname, hostname -f) in your /etc/hosts file?

If fixing this didn't help:

- xsecurelock uses a specific PAM file you specify in ./configure, e.g. /etc/pam.d/common-auth. Is there any PAM module in there that does network requests? Can you try copying this file to a new name, e.g. /etc/pam.d/xsecurelock, ./configure xsecurelock to use it, and then try commenting out parts of it until it works? Note that mistakes in this file can prevent you from unlocking the screen at all (you can use a Ctrl-Alt-F1 text console to kill xsecurelock then). Once you figured out which part is slow, try making this part not access the network.

**Comment by Konfekt** [comment]
Thank you! The error seems gone on OpenSUSE 42.2 (before 42.1) and I'll report back according to your suggestions when it surges again. The only warning is a
```
Xlib:  extension "XFree86-Misc" missing on display ":0".
```
at the start of xsecurelock, but that does not seem to do any harm.

**Comment by divVerent** [comment]
Said extension is used to disable the shortcuts to disable screen grabs, namely:

```
Ctrl+Alt+Keypad-Multiply
Not treated specially by default. If the AllowClosedownGrabs xorg.conf(5x) file option is specified, this key sequence kills clients with an active keyboard or mouse grab as well as killing any application that may have locked the server, normally using the XGrabServer(3x) Xlib function.

Ctrl+Alt+Keypad-Divide
Not treated specially by default. If the AllowDeactivateGrabs xorg.conf(5x) file option is specified, this key sequence deactivates any active keyboard and mouse grabs.
```

If pressing them while the screen lock is running does not let you alt-tab out of the screen lock, you can freely ignore this error or recompile xsecurelock after uninstalling the XFree86-Misc development libraries (or adding #undef HAVE_XF86MISC to the source - there currently is no explicit way to disable this if detected).
