### ISSUE TITLE
What format to use for datetime?

### ISSUE THREAD

**Issue by johnmendrake** [google/xsecurelock#106]
Hey there,
I've been trying to set the time format of xsecurelock to 24h.
From the README it's clear that the environment variable to set is XSECURELOCK_DATETIME_FORMAT but however I sadly don't understand how I'm supposed to specify this format.
An annotation in the README would be nice!
Thanks in advance!!

**Comment by johnmendrake** [comment]
found it!
To make life easier for others to come, I proposed a possible change to README in pull request #107

**Comment by schachmat** [comment]
thx, merged.
