### ISSUE TITLE
Font is miniscule when used with HiDPI display

### ISSUE THREAD

**Issue by UnicodeAlt255** [google/xsecurelock#13]
Is there a way to increase the font size or something? It's not unusuable, but the size of the "Password: " prompt is smaller than my pinky.

**Comment by divVerent** [comment]
Can you try the proposed change https://github.com/google/xsecurelock/pull/15?

This should let you specify the desired font by environment variable.

**Comment by divVerent** [comment]
Proposed change tested and is in master now.
