### ISSUE TITLE
Please make a new release

### ISSUE THREAD

**Issue by svenstaro** [google/xsecurelock#142]
Hey, the last release was in 2020 and some stuff has happened on master in the mean time. I think a new release would be good so distros can package the latest stuff.

**Comment by Barbaross93** [comment]
Hi @divVerent , I apologize if you are not the right person to ping, but you appear to be the most active maintainer for `xsecurelock`.

I was wondering if you could chime in here? Is there a reason for delaying a new release?

**Comment by divVerent** [comment]
Sorry, had missed this. Done: https://github.com/google/xsecurelock/releases/tag/v1.8.0

**Comment by divVerent** [comment]
Oh sorry - will create one.
