### ISSUE TITLE
Sending USR2 to xsecurelock per README kills it instead of displaying the prompt

### ISSUE THREAD

**Issue by Dook97** [google/xsecurelock#148]
## The problem

I find it confusing and annoying to have to press a key to show the password prompt. For such cases the README gives the following instructions:

> To have the authentication process start up without a keypress when the system exits suspend/hibernate, arrange for the system to send the SIGUSR2 signal to the XSecureLock process.
> 
> For example, you can copy the following script to the file `/usr/lib/systemd/system-sleep/xsecurelock`:
> 
> ```bash
> #!/bin/bash
> if [[ "$1" = "post" ]] ; then
>   pkill -x -USR2 xsecurelock
> fi
> exit 0
> ```

But when I do that xsecurelock simply doesn't engage and lets the user right through without any password.

## My setup

I'm using Arch and have xsecurelock installed from its repositories (haven't built it myself). I invoke xsecurelock thusly in my .xinitrc:

`env XSECURELOCK_PASSWORD_PROMPT=time_hex xss-lock /usr/bin/xsecurelock &`

---

Obligatory: *"Sorry, I'm a newbie and the mistake is most probably due to me not knowing wth I'm doing :p"*

**Comment by timakro** [comment]
The feature is not released yet. I'm also hoping for a release :)

**Comment by Dook97** [comment]
Fixed in the last release.
