### ISSUE TITLE
XScreensaver module doesn't handle multiple screens correctly

### ISSUE THREAD

**Issue by julianandrews** [google/xsecurelock#16]
Since many of the `xscreensaver` hacks don't really look right across multiple screens, `xscreensaver` itself runs a separate hack for each monitor. However, `xsecurelock` is just picking a single hack from the `/usr/lib/xscreensaver` directory which often looks silly on 2+ screens.

I spent a little time digging into the `xscreensaver` code to get a sense of what would be involved in fixing this. For each screen `xscreensaver` creates a window, forks, sets `XSCREENSAVER_WINDOW` and `DISPLAY` environment variables to match the new window, and then runs a hack (using `execvp`). The hacks are all written to draw to the `XSCREENSAVER_WINDOW`.

Based on how much `xscreensaver` code is involved in doing this (there are about 1000 lines just devoted to figuring out the screen configuration), I feel sort of bad reporting this as a bug, but it would be nice if it worked like the original program. Possibly a version that assumes RandR for the monitors would be simple enough, and work for most modern setups - figuring out the monitor arrangement is most of the work in the `xscreensaver` code!

**Comment by divVerent** [comment]
You're totally right with this issue. However, I'm unsure of how to handle
it without breaking the security design of xsecurelock - I really don't
want the main process to have such complexity, given this is an easy way to
screw up and have the screensaver die, revealing the session below.

An idea could be solving this in a wrapper - a xscreensaver-like hack that
accepts XSCREENSAVER_WINDOW, creates subwindows per screen, and runs
another xscreensaver hack inside. Of course it'd also have to listen to
configuration changes.

**Comment by divVerent** [comment]
Created a branch divVerent/xrandr which adds this support to auth_pam_x11 first. The only visible change should be that on multiscreen setups with differently sized screens, the password prompt is now always properly centered on each screen.

Planning to later add a multiplexer for screensaver hacks that uses the same library.

**Comment by schachmat** [comment]
Should be fixed by the latest patches from divVerent.
