### ISSUE TITLE
Accessibility: Add sound notifications in different stages

### ISSUE THREAD

**Issue by schachmat** [google/xsecurelock#17]
Something like an ascending interval when the password input is requested, descending interval on successfully unlocking and three low frequency fast beeps on authentication failures should work fine.

**Comment by divVerent** [comment]
Sounds good... just for context, there's generally two choices to do that: PC speaker (via XBell(), and maybe some other calls to change frequency), or proper audio.

And in case of proper audio, we can argue about calling an external tool (aplay, paplay) for this or doing it ourselves. Both should be pretty harmless in the auth component.

**Comment by divVerent** [comment]
We now have some XBell based sounds one can enable with `XSECURELOCK_AUTH_SOUNDS=1`.
