### ISSUE TITLE
GPU reset / X11 crash unlocks session

### ISSUE THREAD

**Issue by gfarrell** [google/xsecurelock#184]
For some reason (I'm still trying to determine) my GPU reset which crashed the X11 server. This resulted in me being kicked into an _unlocked_ session in the login TTY, from which I can do ... whatever I want, including starting a new graphical session.

I had believed this was something the Xsecurelock security model prevented by separating processes out, but that is the intention and it doesn't work, or I have misconfigured it and it doesn't work, or I was incorrect in this belief.

`xsecurelock` is setup as follows in my i3 configuration:

```
exec --no-startup-id xset s 300 5
exec --no-startup-id xss-lock -n /usr/lib/xsecurelock/dimmer -l -- xsecurelock
```

**Comment by jocke-l** [comment]
If you're manually starting the X11 server with `startx`, make sure you run it as `exec startx`. This will replace your login shell with `startx`, so if it exits, you will be forced to login again.

It might help to do this automatically in you shell's configuration by checking if X11 is running and if not, do `exec startx`. This will allow you to still use the TTY if you want.

**Comment by gfarrell** [comment]
Ok, that's a good tip. I've done that and it does the desired thing (prevents me leaving an unlocked session lying around). Thanks.

I'll close this issue in that case.
