### ISSUE TITLE
$XSS_SLEEP_LOCK_FD mechanism does not distinguish success and failure

### ISSUE THREAD

**Issue by divVerent** [google/xsecurelock#19]
We currently support xss-lock's notification mechanism directly.

However, it relies on closing a file descriptor to signal completion - something that also happens normally when a process dies.

What makes things worse is that a caller can't reliably wait for FD closure then waitpid(pid, WNOHANG) for success/failure status of the screen lock, as the kernel first closes all open FDs, then does lots of other stuff, and only at the end marks the process as zombie for waitpid to reap.

I therefore suggest designing an alternate mechanism that handles xss-lock's use case in a wrapper.

**Comment by schachmat** [comment]
As discussed offline we could use the same approach as in https://git.suckless.org/slock/tree/slock.c#n377 where the successful lock notification does not trigger on failure.

**Comment by divVerent** [comment]
The decision here is to keep both mechanisms as they fulfill different purposes.

The FD is closed both on success and failure - the command will only be run on success.

**Comment by divVerent** [comment]
Good case:

[rpolzer@heatersgonnaheat xsecurelock -> divVerent/notify-of-lock]$ sleep 2; date +%s.%N; 
1516124340.971822108
1516124341.110058461
0
1516124354.865723533

Bad case (trying to invoke screen saver with open Chrome context menu):

[rpolzer@heatersgonnaheat xsecurelock -> divVerent/notify-of-lock]$ sleep 2; date +%s.%N; xsecurelock -- date +%s.%N; echo $?; date +%s.%N
1516124385.659820906
Could not grab pointer.
1
1516124386.798126529

Looking good then.

**Comment by schachmat** [comment]
Nice!
