### ISSUE TITLE
XSECURELOCK_WANT_FIRST_KEYPRESS sounds ambiguous

### ISSUE THREAD

**Issue by divVerent** [google/xsecurelock#21]
I've heard from a user that they thought this variable would imply that xsecurelock (the main process as opposed to the auth helper) "wants" the keypress, thus swallows it and does not send it to the auth helper - which is the exact opposite of what the option actually does (process the event and do send it to the auth helper - here "xsecurelock" would refer to the entire project and not just the main process, thus including the auth helper).

Thus I think we should rename the flag to something less ambiguous. Any ideas?

My best idea for now is XSECURELOCK_USE_FIRST_KEYPRESS_FOR_AUTH but that's quite long...

**Comment by darkfeline** [comment]
`XSECURELOCK_KEEP_FIRST_KEYPRESS`?  Implying that otherwise the first keypress is discarded.

**Comment by schachmat** [comment]
I think `XSECURELOCK_USE_FIRST_KEYPRESS_FOR_AUTH` is better. The config variable name is not something you have to type down all the time and explicit+descriptive is good.

**Comment by Vladimir-csp** [comment]
Maybe Invert it, `XSECURELOCK_DISCARD_FIRST_KEYPRESS`? That would be pretty unambiguous and relatively short.
