### ISSUE TITLE
Feature request: Clear password on CTRL+A 

### ISSUE THREAD

**Issue by janschejbal** [google/xsecurelock#25]
In graphical password input fields, CTRL+A selects the entire text of the input field. Thus, when I mistype the password, I can press CTRL+A, then type the password again. In xsecurelock, this doesn't work and CTRL+A inserts a character.

I do realize that the current behavior is perfectly reasonable, and will 100% understand if this is closed as WONTFIX, but I would find it great if CTRL+A could clear the password entry field.

**Comment by divVerent** [comment]
Hm... Ctrl+A is odd for this, as the expectation would be to not yet delete but wait for a next character first.

In bash, Ctrl+U erases the input line, so I'd rather implement this key combination. Will this work for you too?

(Also, if your PAM login is just a single password, you can also just double-tap the escape key)

**Comment by janschejbal** [comment]
ESC works - it's just a muscle memory thing that may make migration from other graphical screen lockers easier for people who are used to using CTRL+A.

While CTRL+A waiting for the next character would be the "expected" behavior, deleting immediately would probably cover any reasonable use of the combination while being easy to implement/not raising the complexity of the code, and it wouldn't be worse than the status quo.

Implementing CTRL+U probably also makes sense. I haven't tested many screen lockers, but whatever Ubuntu 17.10 uses by default does implement it, so I assume at least some others do too and people will likely be used to it. However, it won't help people with muscle memory for CTRL+A.

**Comment by divVerent** [comment]
Done this for now:

- Implemented Ctrl-U.
- Evaluated some other screen lockers regarding Ctrl-A, but found none of the "minimal" ones that support it.
- Noticed xscreensaver and i3lock both support Ctrl-U.
- Noticed xscreensaver also supports Ctrl-X.

Regarding Ctrl-A, added a comment to further evaluate what to do here for now.

**Comment by divVerent** [comment]
Oh, and also added code to not update the screen or the password on any unrecognized control character. This makes the lack of Ctrl-A support more visible.

**Comment by divVerent** [comment]
Ctrl-A is supported tentatively now (3afa755c9d04933fde18a5c0cb21828147abe945). I've let multiple requests convince me despite not particularly liking it.
