### ISSUE TITLE
Feature request: Make pointer grab optional (if it's safe to do so)

### ISSUE THREAD

**Issue by twifkak** [google/xsecurelock#27]
I use `unclutter -grab -idle 2` (http://www.ibiblio.org/pub/X11/contrib/utilities/unclutter-8.README) to hide the mouse cursor after a couple seconds of inactivity [1]. This is incompatible with xsecurelock. Would it be safe to allow me to disable xsecurelock pointer-grab, on the assumption that my mouse movements/clicks aren't sensitive?

[1] In particular, I like the -grab option, as the default 'createwindow' method causes the cursor to reappear when I use the keyboad to move windows / change workspaces in xmonad, which is frequent.

**Comment by twifkak** [comment]
Note: I just successfully switched to https://github.com/Airblader/unclutter-xfixes, so this is very low priority to me. Feel free to close WAI.

**Comment by schachmat** [comment]
I strongly oppose adding this feature as it gives users another way to shoot themselves in the foot. :)

**Comment by divVerent** [comment]
Making the grab optional is absolutely not safe, as mouse movements and clicks are always sensitive.

For example, if this website is open, there's enough stuff you can copypaste using left clicking, dragging and middle clicking. Sure, this requires an attacker to guess what's on your screen so they know where to copy stuff from - but it's certainly possible.

unclutter-xfixes is really the proper solution here.
