### ISSUE TITLE
auth_pam_x11: want keystroke or similar to open a new login dialog to enable another seat (see below)

### ISSUE THREAD

**Issue by Dupond** [google/xsecurelock#29]
Hello,

I have two users under ArchLinux, and I use lightdm to switch between them.

I use the autostart file of openbox to launch xsecurelock for each of these users, using the following code inspired by the example given [here](https://github.com/google/xsecurelock#automatic-locking) :
```
xset s 180 5
xss-lock -n /usr/lib/xsecurelock/dimmer -l -- dm-tool switch-to-greeter
```

Unfortunately, this example is unusable when the sessions of the two users are both opened at the same time : say I'm using the User1 session (and the User2 session is opened too), when the User2 session is unused for 180 seconds then xsecurelock is triggered and I'm suddenly back to the lightdm greeter...

Best regards,
Dupond

**Comment by divVerent** [comment]
On Sun, Apr 15, 2018, 12:44 AM Dupond <notifications@github.com> wrote:

> Hello,
>
> I have two users under ArchLinux, and I use lightdm to switch between them.
>
> I use the autostart file of openbox to launch xsecurelock for each of
> these users, using the following code inspired by the example given here
> <https://github.com/google/xsecurelock#automatic-locking> :
>
> xset s 180 5
> xss-lock -n /usr/lib/xsecurelock/dimmer -l -- dm-tool switch-to-greeter
>
> Unfortunately, this example is unusable when the sessions of the two users
> are both opened at the same time : say I'm using the User1 session (and the
> User2 session is opened too), when the User2 session is unused for 180
> seconds then xsecurelock is triggered and I'm suddenly back to the lightdm
> greeter...
>
> Best regards,
> Dupond
>

First of all, you're not even using xsecurelock at all, but just my dimming
helper.

Secondly, if you just run xsecurelock rather than dm-tool, it won't
interfere with other sessions. Not sure if this will let you log in as
another user somehow (maybe by ctrl-alt-some f key?).

Thirdly, dm-tool switch-to-greeter won't actually lock - try dm-tool lock.

>

**Comment by Dupond** [comment]
Oh OK, sorry : it seems obvious that I still have a lot to learn...
If I understand well, my problem comes from lightdm, not from xsecurelock. I close this issue then.
However I can't do what you suggest, since "log in as another user somehow" is precisely the hard part for me ;)
Thanx for your answers anyway !

**Comment by divVerent** [comment]
Looks like what you really need then is a way for our auth helper to call `dm-tool switch-to-greeter`, so you can switch to the login dialog instead of unlocking.

Even with that, you may still have to unlock twice at times. I'll reopen this issue to be about multi-user support in general.

**Comment by divVerent** [comment]
Do you know how other screen locker handle this, like, which key combination is used to switch to the greeter to log in as another user normally? I'd like to use the same key combination for that purpose.

**Comment by Dupond** [comment]
Thanx for your attention on this.
Sorry, I don't know which key combination is used by other screen lockers. In fact, I'm not sure if other screen lockers handle this at all...

**Comment by divVerent** [comment]
For now I put this on the most likely key combinations to invoke xsecurelock with, which are Win+L and Ctrl+Alt+L. Basically, press this on the auth screen to get a new login.

You then also need to add `export XSECURELOCK_SWITCH_USER_COMMAND='dm-tool switch-to-greeter'` to your script configuring xsecurelock.

**Comment by Dupond** [comment]
OK ! Thank you for your help.
