### ISSUE TITLE
Can't build due to missing function XScreenSaverQueryExtension

### ISSUE THREAD

**Issue by telotortium** [google/xsecurelock#30]
When building with `--with-pam-service-name=xscreensaver` on 28655342, I get the following error:

```
/usr/local/google/home/rmirelan/misc/build/xsecurelock/helpers/until_nonidle.c:159: undefined reference to `XScreenSaverQueryExtension'
```

This is on Debian, with the `xscreensaver` package installed.

**Comment by divVerent** [comment]
Can you provide your config.log?

The package you need to install is libxss-dev, but if you don't have it, until_nonidle shouldn't be compiled with that option in the first place, and I'd like to see what went wrong.

**Comment by telotortium** [comment]
Uploaded to https://gist.github.com/telotortium/bbdf82be35f3f601d4bd94faf20797f7.

**Comment by divVerent** [comment]
```
HAVE_XSCREENSAVER_EXT_FALSE=''
HAVE_XSCREENSAVER_EXT_TRUE='#'
```

This is good, so the extension is properly detected as missing.

```
HAVE_XSYNC_EXT_FALSE='#'
HAVE_XSYNC_EXT_TRUE=''
```

Instead, you got this one.

So configure did the right thing... but thanks to this info, I now found the real bug.

**Comment by divVerent** [comment]
Also fixed another issue that would have, with libxss-dev missing, created an until_nonidle binary that didn't work without setting any config variables. We now default to the IDLETIME counter when libxss-dev is missing.

**Comment by telotortium** [comment]
Thanks for the quick fix!
