### ISSUE TITLE
Pass options to XSECURELOCK_SAVER

### ISSUE THREAD

**Issue by coramuirgen** [google/xsecurelock#34]
I'd like to run gifs as the screensaver, which mplayer supports, but they would need to loop. Would it be possible to pass options, such as:

`    XSECURELOCK_SAVER='saver_mplayer -loop 10' `

Thanks!

**Comment by schachmat** [comment]
You can just create your own `saver_mplayer_loop` or similar by copying the file and changing what you need. You can also try to set it up using an mplayer config file. I don't think adding this feature as an option would have enough users to warrant the added complexity.

**Comment by coramuirgen** [comment]
I'll do that, thank you.
