### ISSUE TITLE
Enable multimedia keys while screen is locked

### ISSUE THREAD

**Issue by marcotmarcot** [google/xsecurelock#37]
As available in other screen locking software, I can use the multimedia keys while the screen is locked, such as mute, volume up and down. This is a nice feature that is very convenient specially in the workplace where an unmuted laptop can be annoying.

**Comment by divVerent** [comment]
If it were easy to do, it'd already be done... the only other such software I'm aware of is deeply integrated with its respective desktop environment to do just that (and it basically reimplements the entire logic).

Nevertheless, if anyone has a generic idea how to do it, please suggest it... but there are no plans to make XSecureLock require GNOME, Cinnamon, KDE or another specific environment.

**Comment by ashkitten** [comment]
can we just make it redirect the media keys to the root window or something, once captured? (i don't know much about X)

**Comment by divVerent** [comment]
The problem is that typically they are not captured by the root window but
by an "arbitrary" window that happens to have a passive grab for the keys
registered. And there is no API to query those passive grabs.

**Comment by divVerent** [comment]
On Fri, Jul 27, 2018, 17:25 Soumya <notifications@github.com> wrote:

> if anyone has a generic idea how to do it, please suggest it
> Sure, why not :)
>
> What if we had a keyhandler process that receives all keys that aren't
> sent to auth (so all shortcuts, xf86media, etc.), and this process could
> then do whatever it wanted with them?
>
> It would be fairly straightforward to provide keyhandler_cinnamon,
> keyhandler_gnome, keyhandler_xfce, etc., and of course, users could write
> their own for maximum control.
>
Even simpler, could just provide two variables - one being a list of
keysyms to forward, and one being a window ID to forward to. This could be
an instance of sxhkd, xbindkeys where you can do whatever you want. And for
many desktop environments you could put your desired multimedia keys in the
list and set the window ID to whatever listens to the keypresses, which you
can fill from a DE specific script that locates the window with e.g.
xwininfo or xprop.

**Comment by soumya92** [comment]
> Even simpler, could just provide two variables - one being a list of keysyms to forward, and one being a window ID to forward to

Just a few quick comments on this solution:
- Forwarding key events may not work very well, because it would require synthetic events and could be ignored by the DE. (XTest won't work because the grab will route all keys back to xsecurelock).
- List of keysyms will introduce filtering code to the main process, not sure that's something you want to do.

But I like the general idea, and would love to see this make its way into xsecurelock :)
