### ISSUE TITLE
Lost my "Super_L" / "mod" / "windows" key after unlock

### ISSUE THREAD

**Issue by cyrinux** [google/xsecurelock#40]
Hi,

First, thanks for this cool tool :)
Since I use this screensaver, and not before, after unlock I lost my Super_L key (keycode 133).
I have no idea why ...

My keymap is set like this, if this can help.

`setxkbmap fr,us,fr,ru azerty,,bepo, -option "grp:shifts_toggle,compose:caps"`

Do you have an idea about the problem?

Tell me how I can help you.

Thanks

**Comment by divVerent** [comment]
This makes no sense (and for me it still works, I'm using it a lot).

Can you before and after running xsecurelock run "xev" and locate the key events when pressing the key? For me they look like:

```
KeyPress event, serial 30, synthetic NO, window 0x4800001,
    root 0x12c, subw 0x0, time 112756238, (891,801), root:(895,1208),
    state 0x0, keycode 133 (keysym 0xffeb, Super_L), same_screen YES,
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: False

KeyRelease event, serial 33, synthetic NO, window 0x4800001,
    root 0x12c, subw 0x0, time 112758062, (891,801), root:(895,1208),
    state 0x40, keycode 133 (keysym 0xffeb, Super_L), same_screen YES,
    XLookupString gives 0 bytes: 
    XFilterEvent returns: False
```

**Comment by divVerent** [comment]
Diffing of "xmodmap -pm -pk" before and after running xsecurelock might also reveal what's going on.

**Comment by cyrinux** [comment]
Sorry man, I don't understand what happen but I can't reproduce the problem now ... sorry for noise... ;)

**Comment by divVerent** [comment]
No problem - in any case the commands I gave you will probably help you
figure it out whatever it is in the end.
