### ISSUE TITLE
xsecurelock shows white screen under xmonad

### ISSUE THREAD

**Issue by pcc** [google/xsecurelock#41]
To reproduce: Run xsecurelock under xmonad

Expected results: Black screen, password prompt visible

Actual results: White screen, password prompt occasionally flickers into view

I can work around the problem with
```
XSECURELOCK_COMPOSITE_OBSCURER=0 xsecurelock
```
so it certainly looks like a problem with the obscurer window.

**Comment by divVerent** [comment]
Unfortunately I'm too dumb to run xmonad :) but let me ask some questions first.

What compositor are you running (I know xmonad itself isn't one)? Compton, xcompmgr or maybe another?

What options have you set up in it?

**Comment by pcc** [comment]
I'm using xcompmgr.

Upon further investigation the problem appears to be unrelated to xmonad but rather xcompmgr. With this minimal .xsession file:
```
#!/bin/sh

xcompmgr &
exec xterm
```
I see the white screen if I start `xsecurelock` from the terminal, but if I do `killall xcompmgr` first, `xsecurelock` behaves as expected.

**Comment by divVerent** [comment]
See https://github.com/google/xsecurelock/issues/24

Xsecurelock is simply incompatible with xcompmgr - workarounds are
described in that bug.

Personally I'd recommend compton --paint-on-overlay as safest alternative
(may want to also pass --backend glx).

The obscurer window incidentally is specifically there to reduce impact of
this bug - without that window you likely can make screen content flicker
in below the screen lock, but the obscurer window makes sure that if this
bug happens, all you get to see is white.

**Comment by pcc** [comment]
Thanks for the link to that bug. I've switched to compton and that seems to have solved the problem for me, thanks!
