### ISSUE TITLE
Login screen should provide a control for switching keyboard layout

### ISSUE THREAD

**Issue by nhcohen** [google/xsecurelock#42]
If the screensaver engages when I'm using a keyboard layout other than the one used to enter my password, there's no way for me to unlock my screen (unless I had the foresight to set up a keyboard-layout shortcut key). The login screen should have a control for switching keyboard layouts (as found in the cinnamon screensaver).

**Comment by divVerent** [comment]
Try this change:

https://github.com/google/xsecurelock/commit/20cf4320e69fc25843fe6eb215fda009d64315f2

It should be conpatible with Cinnamon's method of switching layouts, but not ibus'.

For ibus users a workaround is to define their "hardware" layouts in Cinnamon (or anything else using Xkb groups to manage multiple layouts) and tell ibus in its settings to "use system keyboard layout", and configure only _one_ physical layout but all the IMEs you need in ibus. Then you'll use ibus' control to enable/switch IMEs, and Cinnamon's control to switch layouts.

To verify, run "setxkbmap -query" and check that it lists all your layouts, not just the currenr one.

**Comment by eyal0** [comment]
The solution sort of works but it makes the panel icon wrong and removes some of the benefits of ibus.
