### ISSUE TITLE
Keyboard layout change message inconsistent with xkb settings.

### ISSUE THREAD

**Issue by asunekants** [google/xsecurelock#46]
Xsecurelock on Debian with Cinnamon, using xkb as the input method.
The key combination I use to change layouts is set to LAlt+LShift via the default Cinnamon keyboard config tool.
However, when the screen is locked, the message says "Press Ctrl+Tab" to switch keyboard layouts."
The message is inconsistent with the actual setting, and is confusing.

**Comment by soumya92** [comment]
Does switching layouts with "Ctrl+Tab" not work for you? If so, can you provide some more details on how you've selected multiple keyboard layouts (i.e. gui settings? xorg.conf?)

**Comment by asunekants** [comment]
Just tested it, and both "Ctrl+Tab" and "LAlt+LShft" do work. I've been using the "LAlt+LShft" combo ever since the move from Windows, ages ago, to the point where it's almost a reflex, so I didn't even think of testing it (Which, in itself, is something to think about).
I assumed Xsecurelock just uses whatever key combo is set up in xkb (which I set up via the Cinnamon "Keyboard" interface), and that the message would reflect that setting.
I'm not sure if this warrants a feature request, but more of a "Confusing UX report".

**Comment by divVerent** [comment]
The difference is, LAlt+LShift is your Xkb setting and Ctrl+Tab is an XSecureLock-specific feature to work around issues people had who did _not_ set up a switch key combination in Xkb and then were stuck on a locked screen with a layout they can't type their password in.

The reason why exactly Ctrl+Tab is simply that you can't set up this one in Xkb, so there can't be any conflicts due to it.

So I'm going to close it - the UI is working properly after all, and the message is true - however if you want to make a patch that detects the key combination actually set up in Xkb and display that instead of Ctrl+Tab when it's set, that'd be awesome.

**Comment by Vladimir-csp** [comment]
I've just built xsecurelock to get it a spin on Debian testing, and this hardcoded message is kind of confusing. Ctrl+Tab does not work, I also see `xsecurelock: XkbGetControls failed` message in stderr. But my standard Alt+Shift shortcut works as always, and a rationale that someone would forget or be unaware of their own layout switching is strange at best.

**Comment by soumya92** [comment]
> Em... How is that even possible? It would basically render the system partially unusable.

You can still use the UI to switch keyboard layouts, even if you have not configured a shortcut for it.

**Comment by Vladimir-csp** [comment]
> You can still use the UI to switch keyboard layouts, even if you have not configured a shortcut for it.

That would be a huge hassle. In my admin practice even the most incompetent users at least knew how to switch layouts with a shortcut.
But I digress. The current layout switching option can be determined from `setxkbmap -query | grep options: | grep -o 'grp:[a-z_]\+_toggle'` So xsecurelock-specific switcher and message can be omitted if it at least exists.
(all available options: `localectl list-x11-keymap-options | grep 'grp:[a-z_]\+_toggle'`).

**Comment by divVerent** [comment]
Fixed XkbGetControls error. Cause: bad documentation in Xkb (I needed none of the fields that can be optionally enabled via the mask, but passing 0 in the mask is invalid).

**Comment by divVerent** [comment]
Other question is, can we somehow inquire from Xkb which toggle key has been set up? Then we could even recommend that one instead.

**Comment by Vladimir-csp** [comment]
> Other question is, can we somehow inquire from Xkb which toggle key has been set up? Then we could even recommend that one instead.

Perhaps, by taking a peek at how `setxkbmap -query` does it? `getServerValues` function seems to be doing it, I'm not very good at reading any deeper than that in C.
