### ISSUE TITLE
Unable to use saver_xscreensaver module

### ISSUE THREAD

**Issue by AuditeMarlow** [google/xsecurelock#48]
I'm on Arch Linux and just installed from the [AUR](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=xsecurelock-git). I've installed `xscreensaver` too and tried using this with `xsecurelock`, but ended up hearing `saver_xscreensaver` must be executable:

```sh
niek at macbook in ~
 ○ env XSECURELOCK_SAVER=saver_xscreensaver xsecurelock
2018-10-02T18:09:15Z 24173 xsecurelock: Executable 'saver_xscreensaver' must be executable.
```

What am I missing here? Running `xscreensaver` on my host system works just fine. Using `xsecurelock` without any options works just fine, too.

**Comment by AuditeMarlow** [comment]
I just saw the PKGBUILD and it states version 0.5 as its build version, which is "outdated" compared to the GitHub repository. I'll try doing a GitHub build...

**Comment by languitar** [comment]
There is already a package for the stable version on AUR: https://aur.archlinux.org/packages/xsecurelock/

However, the git version automatically updates to the latest state. Just the information on the AUR website is outdated as long as I do not update the package manually.

**Comment by AuditeMarlow** [comment]
Thanks @languitar for your feedback. I'll try out the stable AUR package.

Aside from that, building `xsecurelock` from the GitHub repository works just fine too, I suppose I was just on an outdated version. :)

**Comment by razor-x** [comment]
> `xsecurelock 1.8.0-1` is now in Arch Linux official community packages and this still does not work. I get same error: `xsecurelock: Executable 'saver_xscreensaver' must be executable.`

@tuxy I just happened to be trying to get this to work today on Arch and had the same issue.

I can confirm that `/usr/lib/xsecurelock/saver_xscreensaver` does not exist in the [package contents](https://archlinux.org/packages/community/x86_64/xsecurelock/). I tried to build xsecurelock locally, and confirmed that even with `xscreensaver` installed, xsecurelock `./configure` does not detect it and thus does not include `saver_xscreensaver` in the build. (I also tried to force it with a flag, and even though I was able to get `saver_xscreensaver` in the local package, xsecurelock was unable to use it, giving `xsecurelock: No saver selected. Giving up.`).

![image](https://user-images.githubusercontent.com/721372/205522579-e1f28c9e-009a-4ae4-9ec2-a608a1b22714.png)

**Comment by sh1nryu** [comment]
Can confirm I am also having issues using 'saver_xscreensaver', via github install & AUR

**Comment by divVerent** [comment]
So all that happened is that the directory changed?

Is it the same across distros or do we need to autodetect from multiple directories then?

**Comment by divVerent** [comment]
Everything works fine on Debian with this package and no changes to xsecurelock:

```
$ apt policy xscreensaver
xscreensaver:
  Installed: 6.02+dfsg1-2+b1
  Candidate: 6.02+dfsg1-2+b1
  Version table:
 *** 6.02+dfsg1-2+b1 500
        500 http://deb.debian.org/debian bookworm/main amd64 Packages
        100 /var/lib/dpkg/status
```

It still installs into /usr/libexec/xscreensaver though. Not sure if that's a Debian patch or still default.

**Comment by sh1nryu** [comment]
In that case `lib` vs `libexec` seems to depend on your installation method... For myself using a package manager (pacman) installed `xscreensaver` to `/usr/lib/xscreensaver`

**Comment by divVerent** [comment]
Can anyone try if that fix works?

**Comment by walwan** [comment]
yeah, I think this fix works. My build without explicitly specifying the xscreensaver location can correctly detect xscreensaver at the default location.

**Comment by spease** [comment]
I'm running into this issue with the current `extra/xsecurelock 1.8.0-1` package

File list:
```
xsecurelock /usr/
xsecurelock /usr/bin/
xsecurelock /usr/bin/xsecurelock
xsecurelock /usr/lib/
xsecurelock /usr/lib/xsecurelock/
xsecurelock /usr/lib/xsecurelock/auth_x11
xsecurelock /usr/lib/xsecurelock/authproto_pam
xsecurelock /usr/lib/xsecurelock/dimmer
xsecurelock /usr/lib/xsecurelock/pgrp_placeholder
xsecurelock /usr/lib/xsecurelock/saver_blank
xsecurelock /usr/lib/xsecurelock/saver_mplayer
xsecurelock /usr/lib/xsecurelock/saver_mpv
xsecurelock /usr/lib/xsecurelock/saver_multiplex
xsecurelock /usr/lib/xsecurelock/until_nonidle
xsecurelock /usr/share/
xsecurelock /usr/share/doc/
xsecurelock /usr/share/doc/xsecurelock/
xsecurelock /usr/share/doc/xsecurelock/CONTRIBUTING
xsecurelock /usr/share/doc/xsecurelock/LICENSE
xsecurelock /usr/share/doc/xsecurelock/README.md
xsecurelock /usr/share/doc/xsecurelock/examples/
xsecurelock /usr/share/doc/xsecurelock/examples/saver_livestreams
```
