### ISSUE TITLE
Option to run script on auth fail

### ISSUE THREAD

**Issue by p3lim** [google/xsecurelock#49]
Would be nice if we could add a script that'd be called when someone types the wrong password.
One way this could be used (as an example); take a picture with the camera on a laptop.

**Comment by p3lim** [comment]
Can be done with PAM modules:
https://bbs.archlinux.org/viewtopic.php?id=220506

**Comment by divVerent** [comment]
I agree the PAM module way is definitively the right way here, as this
script may run with elevated privileges (especially on FreeBSD) and thus
requiring system wide configuration to run specific scripts from there
would be a good idea for security reasons.
