### ISSUE TITLE
Debian/Ubuntu Packaging

### ISSUE THREAD

**Issue by Mezzle** [google/xsecurelock#5]
Hi,

Wondering if Debian/Ubuntu packaging would be something you'd be interested in ?

(I'm an Ubuntu & Debian Developer)

**Comment by wernight** [comment]
Also to disable the `gnome-screensaver` without uninstalling you can run:

    $ dconf gsettings set org.gnome.desktop.screensaver lock-enabled false

It seems that Unity doesn't have a way to hack around it, see https://www.jwz.org/xscreensaver/man1.html but for other releases, consider hacking by replacing `/usr/bin/gnome-screensaver-command` by:

    #!/bin/sh
    exec /usr/local/bin/xsecurelock auth_pam_x11 saver_blank || kill -9 -1

**Comment by schachmat** [comment]
I'm currently working on debian packaging in the debian_packaging branch. When the package looks good, we'd also like to add it to the upstream debian repository.

**Comment by schachmat** [comment]
The packaging code has been merged into the master branch earlier today. I'm aiming at submitting the package to Debian in 2-3 months.

**Comment by Mezzle** [comment]
@schachmat thanks for that, I've not had a chance to look into it properly.  Please give me a shout though if you need a sponsor - mez AT debian DOT org

**Comment by fabiogermann** [comment]
@schachmat did you make any progress in the direction of submitting the packages?

**Comment by fabiogermann** [comment]
@schachmat will you be publishing for Debian/Ubuntu only or also Fedora?

**Comment by schachmat** [comment]
Finally filed the ITP at https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=909020. I already have a sponsor for the upload, so it shouldn't take too long now.

**Comment by Artanicus** [comment]
Any updates? The ITP seems to have gotten largely ignored.

**Comment by schachmat** [comment]
Yes, I'm aware and sorry for the delay. I hope to find some time to update the debian branch and then poke one of the maintainers to sponsor the upload within the next 3 weeks. If you don't hear anything new by then, feel free to poke me here again. :)

**Comment by alexzorin** [comment]
Hi @schachmat, any news on Debian packaging?

**Comment by schachmat** [comment]
xsecurelock is waiting in the https://ftp-master.debian.org/new.html queue for ~1 month now.

**Comment by schachmat** [comment]
The package doesn't seem to be available in unstable yet. I'd like to keep this issue open until it is (and then close it celebratorily).

**Comment by schachmat** [comment]
And it has been merged. :)
 https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=909020#10
https://tracker.debian.org/pkg/xsecurelock
