### ISSUE TITLE
Clock on the unlock screen

### ISSUE THREAD

**Issue by EhsanKia** [google/xsecurelock#57]
Currently, there's a clock on the stand by screen, but as soon as you move your cursor and the black login screen comes, you can't see the time anymore. Is there any chance we can get a simple minimal clock on that page?

**Comment by divVerent** [comment]
Just set XSECURELOCK_SHOW_DATETIME=1.

**Comment by EhsanKia** [comment]
Sorry for reviving this old issue, but I never managed to get this to work.

I have `export XSECURELOCK_SHOW_DATETIME=1` in my .xsecurelockrc file, and I still don't see a clock. Are we talking about the same screen? The one where you enter your password.

I also have `export XSECURELOCK_SAVER="{XSECURELOCK_SAVER:-saver_blank}"` and that one works as expected, but the clock one does not work for me. Am I doing something wrong? Can you confirm that it still works? I've tried restarting multiple times but still nothing.
