### ISSUE TITLE
Feature: Respect Stacked PAM Modules (MFA Support)

### ISSUE THREAD

**Issue by guygma** [google/xsecurelock#58]
Given the main focus of this project is on security (which I whole-heartedly support), I would expect that a feature-goal is for any multi-factor authentication enforced by stacked PAM modules to be respected by default. What is the status of MFA support in `xsecurelock`? If it is not complete, what would need to be done for that to become a first class feature if in line with the project goals?

**Comment by guygma** [comment]
Ok, so I spent some time getting this "working" on my system. The auth block of my `system-auth` looks like this:

```
auth      required  pam_unix.so     try_first_pass nullok
auth	  requisite pam_securid.so
auth	  [default=1 success=ignore]  pam_succeed_if.so user ingroup hasyubi
auth	  requisite pam_yubico.so mode=challenge-response chalresp_path=/var/yubico
auth      optional  pam_permit.so
auth      required  pam_env.so
```
The `pam_securid.so` is for a local 2FA to a company server, which can only be bypassed for users in the `hasyubi` group. In that case, though, 2FA is still enforced. From what I could surmise from output to the journal, all the authentication was successful but the screen would still not unlock. Changing the `requisite` to `required` has no effect. It is only if `requisite` is changed to `sufficient` that I can successfully unlock my screen. This seems like very strange behavior, not the least of which because it takes a good 30 seconds or so to actually complete. 

So it seems that while this feature is technically supported, some rough edges remain. Is this the known status or might there be some setting that I am missing?

**Comment by divVerent** [comment]
It should work just fine - I'd need more debug info for this.

Can you try authenticating by running authproto_pam from a terminal? Sorry, it's a bit tricky to try that out, but the essence is to respond to prompts like

```
P 10
Password:
```

by "packets" like:

```
p 5
abcde
```

(where the response line contains the number of characters in the response).

**Comment by divVerent** [comment]
Also, can you link to source code of pam_securid and pam_yubico? May help figuring out what's wrong there.

One issue I expect there is that 2FA systems tend to want a prompt for something that isn't keyboard input - and PAM APIs simply don't support that, so they'll have to work around that somehow.

From what I found, pam_yubico expects the key on the keyboard input, so it uses a regular PAM prompt (and the yubikey outputs the key as characters on the keyboard). Isn't this the really old way?

**Comment by guygma** [comment]
I would **love** to link you to the source of `pam_securid`... Alas, it is [proprietary](https://community.rsa.com/community/products/securid/authentication-agent-pam). The source of [`yubico_pam`](https://github.com/Yubico/yubico-pam) is available thought. 

So I have not actually unlocked the screen while having to pass the  `pam_yubico` challenge because my rules only require that for root (company/government policy). For my user I get a password prompt followed by a passcode prompt from `pam_securid` just fine, but then the screen hangs at "Processing..." for a good 20 to 30 seconds before unlocking successfully. 

Your comment about the module not properly adhering to PAM APIs seems entirely possible. With the information I have given about the hanging before success and the (unwarranted) requirement of the `sufficient` option, are there certain logs (perhaps generated with specific switches to xsecurelock or the pam modules) that would be most helpful in clarifying the origin?

The output you requested:

```
gmarcus@gmarcus-l ~ % /usr/lib/xsecurelock/authproto_pam                                                      :(
P 10
Password:
p 9
*********
P 29
Enter an unused RSA passcode:
p 6
******
[FAIL: Returns to original "Password" prompt.]
```
Relevant bits in `journalctl -xe`:

```
Dec 10 14:34:14 gmarcus-l.spectral.com authproto_pam[10628]: pam_unix(system-auth:auth): conversation failed
Dec 10 14:34:14 gmarcus-l.spectral.com authproto_pam[10628]: pam_unix(system-auth:auth): auth could not identify password for [gmarcus]
```
which is quite odd since I can unlock the screen... I just tried again to be sure and to provide the only additional content posted to the journal:
```
Dec 10 14:43:02 gmarcus-l.spectral.com authproto_pam[15320]: pam_succeed_if(xsecurelock:auth): requirement "user ingroup hasyubi" not met by user "gmarcus"
```
which is just telling me what I expect: no need to provide Yubikey for 2FA as I already passed the SecurID. 

Hopefully this helps you get some insight; I'm just puzzled as to where the confusion is coming from internally. The only thing that stands out to me from the journal is that the error is raised by `pam_unix`, which makes me wonder if there is some subtle issue with passing over control between the stacked modules.

**Comment by divVerent** [comment]
Normally I'd suspect that your issue is in your PAM config - but I can't say for sure.

**Comment by divVerent** [comment]
```
       required
           failure of such a PAM will ultimately lead to the PAM-API returning failure but only after the remaining stacked modules (for this service and
           type) have been invoked.
```

Try to temporarily set pam_unix to be requisite rather than required. Then you should get possible pam_unix errors instantly. Try with authproto_pam then - and get past pam_unix first before looking at the rest.

**Comment by divVerent** [comment]
Closing due to no response; maybe the problem has resolved since?

If not, I'd really need some information to reproduce this using software and devices I have and don't need to order from RSA.
