### ISSUE TITLE
make fails, version.c is missing

### ISSUE THREAD

**Issue by maximbaz** [google/xsecurelock#59]
```
if git describe --always --dirty >/dev/null 2>&1; then \
        echo "const char *const git_version = \"` \
                git describe --always --dirty \
        `\";" > version.c; \
else \
        : version.c must exist in non-git builds.; \
        cat version.c; \
fi
cat: version.c: No such file or directory
make: *** [Makefile:2033: version.c] Error 1
```

> version.c must exist in non-git builds.;

We are downloading tarball from Github releases, it doesn't contain `version.c`. Please provide a release archive that contains this file, for package distribution purposes. Thanks!

**Comment by languitar** [comment]
As the maintainer of the archlinux AUR package for xsecurelock I can add to this that I didn't see this issue because I have tried building the software from inside the packaging git repository. Git seems to traverse up the directory hierarchy and then uses information from a wrong git repo for splicing into xsecurelock. Hence, the build system also needs to shield against this case. I would propose to change the logic here in such a way that, in case `version.c` exists, `git describe` must not be called.

**Comment by divVerent** [comment]
Yeah, version.c is required. Hm... need to check what I can do to make github build a working tarball.

"make dist" includes a version.c matching the release, that was the idea. A simple "git archive" won't work.

Obvious solution: add a package management side hack to add a version.c including the package version.

**Comment by maximbaz** [comment]
Could you change the Makefile so that we can just provide version as a parameter? 

make VERSION=1.2.3

**Comment by divVerent** [comment]
For now, to fix the most pressing issue, I attached a "make dist" tarball to the release on github.

As for the VERSION= flag - that could work, but I'd still have to make it generate a version.c. Will do that for now.

**Comment by divVerent** [comment]
Note: had to call the variable GIT_VERSION instead of VERSION, as VERSION already comes from autoconf and is a bit too coarse (it's simply whatever is in configure.ac, while I want to include the exact git commit a build is based on to ease debugging).

**Comment by divVerent** [comment]
Otherwise, I wonder if I should switch to something like v1.2-<hash> instead, where <hash> is a hash of all the source files; could then provide a script to map that back to a git revision by brute forcing (for patched source it then would be impossible to identify the exact origin version).

**Comment by maximbaz** [comment]
I think packages based on official releases should just use the git tag name (`v1.2`), and only when building from source the version should instead have information about specific commit hash. It is always possible to know to which commit a given tag points, but in most cases it will save you time because you won't need it, if you see `v1.2`, you know this person is using latest official release.
