### ISSUE TITLE
Need examples for altering font size

### ISSUE THREAD

**Issue by RedTailBullet** [google/xsecurelock#72]
I've checkout #13 and #15 but I am still confused on how to alter the font size and the name of the font. Could you please provide some examples? Thank you.

**Comment by divVerent** [comment]
Documentation says:

*   `XSECURELOCK_FONT`: X11 or FontConfig font name to use for `auth_x11`.
    You can get a list of supported font names by running `xlsfonts` and
    `fc-list`.

My personal setting is `monospace:size=12` (a fontconfig pattern). xlsfonts outputs stuff like `-bitstream-charter-bold-r-normal--33-240-100-100-p-206-iso8859-1` that should work as well, and use a large font size.

**Comment by RedTailBullet** [comment]
> Documentation says:
> 
>     * `XSECURELOCK_FONT`: X11 or FontConfig font name to use for `auth_x11`.
>       You can get a list of supported font names by running `xlsfonts` and
>       `fc-list`.
> 
> 
> My personal setting is `monospace:size=12` (a fontconfig pattern). xlsfonts outputs stuff like `-bitstream-charter-bold-r-normal--33-240-100-100-p-206-iso8859-1` that should work as well, and use a large font size.

I tried something like `mono:size=96` but it doesn't work. Xsecurelock told me that it can't find the font. However, with `fc-match` and `fc-pattern`, I can verify that this pattern is viable.

**Comment by gspe** [comment]
Try with `mono-96` should work

**Comment by divVerent** [comment]
What happens if you explicitly pass `--with-xft` to ./configure when you build?
