### ISSUE TITLE
Can I replace "xset s activate" with "xset dpms force suspend"?

### ISSUE THREAD

**Issue by RedTailBullet** [google/xsecurelock#73]
When using `xset s activate`, the screen will not be turned off which increase power usage. So I tried `xset dpms force suspend`. I found out that xsecurelock also lock the screen after that. Will the latter command be sufficient as well? Or do you recommend using another method?

**Comment by divVerent** [comment]
To be honest, I don't know. It seems like it does.

Note that this command isn't implemented by xsecurelock at all; this is xss-lock's and X.org's doing. Also, be aware that "xset dpms force suspend" doesn't do anything for screens not supporting DPMS (if they even exist).

However there's a simple solution: just use xset s activate dpms force suspend. Sure harmless, and should just work.

Or, set XSECURELOCK_BLANK_TIMEOUT=1 and XSECURELOCK_BLANK_DPMS_STATE=suspend to basically run xset dpms force suspend once second after locking.

**Comment by RedTailBullet** [comment]
The issue I am facing now is that while trying to use i3 for activating screen lock, I can't make it work well with the dpms command. After the screen is suspended, it always awake after around 1 seconds and "leaking" the screen for a split second. Then the screen stays on for 300 seconds (which is set by me as the timeout time for the screen).

Maybe I should be using another shortcut app for it.

**Comment by RedTailBullet** [comment]
Right, that seems to be an issue with the saver option of xsecurelock. Once I disabled the saver for it, it works as expected.

**Comment by divVerent** [comment]
Can you provide an exact reproduction instruction for how it leaks screen
content? That seems more important to fix than the rest here.

There may indeed be something that isn't quite working with suspend
interaction - I just couldn't reproduce it yet. Even though I am using i3
too.

**Comment by RedTailBullet** [comment]
Well, I am using `xss-lock -n dimmer -l -- xsecurelock` with i3 (running xss-lock in i3's config). And I set an hotkey `win+ctrl+l` for the `xset s activate dpms force suspend`.

In some cases, once you press the hotkey, the screen suspends normally, but after around 1 second, the screen wakes up again and display the content for a split second. Then the screen stays awake and is locked.
The screen leak only happens on the first run it seems.

**Comment by divVerent** [comment]
Oh I remember the core issue here then.

You launch xsecurelock when pressing a key - but the release event wakes up
the screen again.

The cleanest solution is to find a way to run the screen lock on the
release event.

If not, the next cleanest way is to indeed delay the DPMS command until
after you released the key, by setting the variable I suggested.

Somewhat more dirty would be binding the key to just 'sleep 1; xset s
activate dpms force suspend'. But that might not fully help - it could be
that your monitor or your GPU then still remembers old screen content until
waking up even though according to X it is long gone.

**Comment by RedTailBullet** [comment]
Fortunately the hot-key app I used `xbindkeys` do support the release event.
