### ISSUE TITLE
Google Chrome gets blank after unlocking

### ISSUE THREAD

**Issue by nibogd** [google/xsecurelock#8]
After unlocking the screen the Chrome window sometimes gets blank, repaints only on Chrome restart (via `killall chrome`,  hotkeys don't work) or after taking a screenshot. No problems with other GTK2 applications.

Environment: Arch Linux, bspwm

![Screenshot](http://i.imgur.com/JMz3WS4.png)

**Comment by divVerent** [comment]
Very interesting bug - and oddly I'm using Chrone too yet not getting that bug.

I also am using a non-compositing window manager.

Here's some questions:

- Does Chrome work again if you switch virtual desktops / minimize and restore its window? If yes, there may be an easy workaround.
- Can you grab a backtrace from Chrome in the hung state using gdb (or possibly by sending SIGSEGV to it)?
- Can you try disabling XComposite support? Either by telling X.org to not provide that, or by commenting out "am__append_2 = -DHAVE_COMPOSITE" in Makefile after running configure?

**Comment by nibogd** [comment]
1. No, doesn't work after switching desktops (bspwm is a tiling wm, no minimizing). But it works after taking a screenshot, which is strange.
2. Sorry, couldn't find out how should i do this (not familiar with gdb)
3. Is it possible to do this without recompiling Xorg?

**Comment by divVerent** [comment]
Oh, I meant recompiling xsecurelock (not all of Xorg) after that change.

I.e.:

./configure --with-pam-service-name=... ...
vim Makefile
(do the change as above)
make

If that helps, I'll implement a configure option for that.

Alternatively, you can disable the extension in xorg.conf, but let's just
go with the Makefile change for now.

**Comment by nibogd** [comment]
Done that, Chrome still gets blank
Xsecurelock prints this to console:
```
~ $ xsecurelock 
Received unexpected event 19.
Received unexpected event 19.
```
May it be somehow related?

**Comment by divVerent** [comment]
Oops, sorry for the spam message. It is certainly unrelated though:

#define MapNotify               19

The Chrome issue remains to be solved then, I suppose.

Can the issue be reproduced in another window manager?

**Comment by divVerent** [comment]
Also, does xrefresh (http://manpages.ubuntu.com/manpages/wily/man1/xrefresh.1.html) succeed at fixing Chrome? I'd have an idea what may be causing this then.

If this helps, then the Makefile change I suggested above should help too.

**Comment by nibogd** [comment]
I've installed openbox,  the bug can be reproduced there after locking and unlocking two times.

Using xrefresh i can only change Chrome window color, but not fix it…
![](http://i.imgur.com/dgQS7lw.png)

**Comment by nibogd** [comment]
I've decided to use `compton` as a compositing manager, the problem solved itself. Thank you, xsecurelock is the best locker! ;)

You may close the issue, but it still doesn't work without compositing.

**Comment by divVerent** [comment]
Hm... without any way to reproduce this on any of my devices, I'll close it for now, but if anyone is affected by it, please reopen then and add details.

Note that I nowhere have any AMD GPUs - it's quite possible it's the driver's fault.
