### ISSUE TITLE
Mouse motion will only bring up auth menu once.

### ISSUE THREAD

**Issue by evolarium** [google/xsecurelock#81]
For the motion events, PointerMotionHintMask is set so that only one MotionEvent is sent.  However, it doesn't look like there are any state changes that reset this so that another MotionEvent will be received.

A quick test is to lock the screen, move the mouse (brings up the auth window), hit escape, then move mouse again (blank screen).

[This page](https://tronche.com/gui/x/xlib/events/keyboard-pointer/keyboard-pointer.html) says that calling XQueryPointer() or XGetMotionEvents() will reset this so another MotionEvent can be received.

Calling XQueryPointer in the switch case MotionNotify seems to fix it for me, but I'm not sure this is the proper place or use for it.
[motionnotify.txt](https://github.com/google/xsecurelock/files/3303228/motionnotify.txt)

**Comment by schachmat** [comment]
Great catch, thanks for debugging! I too noticed that sometimes the mouse doesn't bring up the auth prompt, but didn't notice that works on the first time. We should definitely fix this.

**Comment by divVerent** [comment]
Oops indeed, I had accidentally included PointerMotionHintMask, hoping I get "all pointer events".
