### ISSUE TITLE
gcc versions and C dialect compatibility

### ISSUE THREAD

**Issue by SpiderPig** [google/xsecurelock#85]
Failure to build on older versions of gcc (Tested with 4.8 on Centos) due to C99 standards dialect.  Older versions of gcc seem to require explicitly enabling C99 standards compatibility as compiler opts.  This is fixed simply by specifying -std=gnu99 in the CFLAGS.

This is the compilation error.
```
helpers/auth_x11.c: In function 'Prompt':
helpers/auth_x11.c:1098:11: error: 'for' loop initial declarations are only allowed in C99 mode
           for (size_t i = 0, bit = 1; i < DISCO_PASSWORD_DANCERS;
           ^
```
Here is what I'm using to build for gcc 4.8 on Centos7.

```diff
--- a/Makefile.am
+++ b/Makefile.am
@@ -14,7 +14,7 @@
 
 CLEANFILES =
 
-AM_CFLAGS = -Wall -Wextra -D_POSIX_C_SOURCE=200112L -D_XOPEN_SOURCE=600
+AM_CFLAGS = -Wall -Wextra -D_POSIX_C_SOURCE=200112L -D_XOPEN_SOURCE=600 -std=gnu99
 
 macros = \
 	-DHELPER_PATH=\"$(pkglibexecdir)\" \
```

**Comment by divVerent** [comment]
That's a mistake; I'll fix it. I am trying to keep the code on C89 for compatibility but failed in this instance.

**Comment by divVerent** [comment]
Fixed; wonder if there's any better way to declare this. For now I want to use C89 with C++-style comment syntax (for iwyu); in the future I want to move to C99 but first have to figure out how to teach autoconf that.
