### ISSUE TITLE
Keyboard lock shortcut

### ISSUE THREAD

**Issue by andromeda306** [google/xsecurelock#86]
Hi guys, despite having read an extensive amount of info, I may have missed something obvious. Is there a way to trigger xsecurelock lockscreen via a system defined keyboard shortcut .e.g Win+L ? I'm looking to dump cinnamon-screensaver due to its instability and am having a tough time in finding concrete use instructions/guides for xsecurelock. Cheers.

**Comment by opentokix** [comment]
@andromeda306 That is something you configure in your window manager that in turn invoke the xsecurelock program. This program is not running always.

**Comment by schachmat** [comment]
Correct. FYI: We also have a pending discussion for upstreaming a patchset helping with using other screensavers from Cinnamon: https://github.com/linuxmint/cinnamon-screensaver/pull/323

As a very simple way this could also work: Disable the screensaver in the Cinnamon Settings, then create a new Keyboard shortcut in the Cinnamon settings which launches the xsecurelock binary. You'll loose automatic locking after timeout and won't be able to lock using the Cinnamon menu. For timeout locking see https://github.com/google/xsecurelock#automatic-locking
