### ISSUE TITLE
suspending when already locked

### ISSUE THREAD

**Issue by Konfekt** [google/xsecurelock#9]
With the following settings in `/etc/systemd/logind.conf`
```
SuspendKeyIgnoreInhibited=yes
```
one can suspend by pressing the suspend button when the screen is locked (by xsecurelock).

If `xfce4-power-manager` is running,  then suspend by the suspend button  is no longer possible.

However, closing the lid always suspends, with or without `xfce4-power-manager`.

- Why is that? 
- How to make xsecurelock allow suspending by pressing the suspend button even if  `xfce4-power-manager` is running?

**Comment by divVerent** [comment]
xsecurelock isn't doing anything to talk to systemd, so honestly - no idea. Maybe ask the xfce4 people?

**Comment by Konfekt** [comment]
For reference:

http://docs.xfce.org/xfce/xfce4-power-manager/faq#how_can_i_make_logind_handle_button_events_instead_of_xfce4-power-manager
