### ISSUE TITLE
feature request: respect or introduce some cursor-blink setting

### ISSUE THREAD

**Issue by archenemies** [google/xsecurelock#90]
I have

    gsettings set org.gnome.desktop.interface cursor-blink false

which works for most GTK apps.

For your program, I guess I have to do

    XSECURELOCK_PASSWORD_PROMPT=hidden xsecurelock

Maybe since you're not linking to GTK it's not so simple as querying my GTK setting. But it would be nice if one of the other prompt styles respected a cursor blink setting, whether it's application-specific or not.

The usual argument that people can't find the cursor unless it blinks doesn't seem to apply here.

**Comment by divVerent** [comment]
What do you want the blinking setting to do? Just on/off, or would you also require the blink time to be configurable (which would be harder)?

**Comment by archenemies** [comment]
Just on/off is enough. Thanks.

**Comment by divVerent** [comment]
Was simple enough, done.

XSECURELOCK_AUTH_CURSOR_BLINK=0

**Comment by archenemies** [comment]
Thank you!
