### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [google/xsecurelock#96]
Memory is allocated
https://github.com/google/xsecurelock/blob/db18f779b48622619c7343adf0821ad607909fbb/helpers/authproto.c#L167

but at the end of function, never free it

**Comment by divVerent** [comment]
In case of an error, there is indeed a leak, but the calling code then always immediately exits, so this leak does not matter.

Fixing it anyway though, to prevent future issues from this.

**Comment by divVerent** [comment]
Thanks!
